### ISSUE TITLE
Traceback with latest python update on -current

### ISSUE THREAD

**Issue by LiohMoeller** [dslackw/sun#9]
With the latest python updates in -current I got a traceback while trying to start sun or to activate the daemon:

```
Traceback (most recent call last):
  File "/usr/lib64/python3.8/site-packages/sun/gtk/status_icon.py", line 163, in show_check_updates
    data, packages = check_updates()
  File "/usr/lib64/python3.8/site-packages/sun/cli/tool.py", line 59, in check_updates
    packages = fetch()
  File "/usr/lib64/python3.8/site-packages/sun/utils.py", line 108, in fetch
    r = url_open(mir)
  File "/usr/lib64/python3.8/site-packages/sun/utils.py", line 44, in url_open
    con = http.request('GET', link)
  File "/usr/lib64/python3.8/site-packages/urllib3/request.py", line 75, in request
    return self.request_encode_url(
  File "/usr/lib64/python3.8/site-packages/urllib3/request.py", line 97, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/usr/lib64/python3.8/site-packages/urllib3/poolmanager.py", line 319, in urlopen
    conn = self.connection_from_host(u.host, port=u.port, scheme=u.scheme)
  File "/usr/lib64/python3.8/site-packages/urllib3/poolmanager.py", line 234, in connection_from_host
    return self.connection_from_context(request_context)
  File "/usr/lib64/python3.8/site-packages/urllib3/poolmanager.py", line 244, in connection_from_context
    pool_key_constructor = self.key_fn_by_scheme[scheme]
KeyError: 'ftp'
```
The Daemon does not start anymore and the 'check updates' functionality does not return a result.

**Comment by LiohMoeller** [comment]
Reported on GitLab
